const card = document.createElement('li');
card.classList.add('card');
const cbContainer = document.createElement('div');
const cbInput = document.createElement('input');
const check = document.createElement('span');
const item = document.createElement('p');
const editInput = document.createElement('input');
const button = document.createElement('span');
const edit = document.createElement('span');
const icon = document.createElement('i');
const iconEdit = document.createElement('i');
